<<<<<<< HEAD
# Generated by Django 4.1.6 on 2023-05-27 18:07
=======
# Generated by Django 4.2.1 on 2023-05-27 20:19
>>>>>>> 57f915a9eb62c71c210cf535977fa26cd6d5d82b

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('firesale', '0018_remove_message_item_message_bid'),
        ('user', '0002_profile_name'),
=======
    dependencies = [
        ("user", "0002_profile_name"),
>>>>>>> 57f915a9eb62c71c210cf535977fa26cd6d5d82b
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_item', to='firesale.item'),
=======
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="favorite_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorite_item",
                to="firesale.item",
            ),
>>>>>>> 57f915a9eb62c71c210cf535977fa26cd6d5d82b
        ),
    ]
