# Generated by Django 4.1.6 on 2023-05-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0019_remove_review_from_member_remove_review_to_member_and_more'),
        ('user', '0002_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_item', to='firesale.item'),
        ),
    ]
