# Generated by Django 4.2.1 on 2023-05-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firesale", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("bid_amount", models.IntegerField()),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("img_url", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=1000)),
                ("price", models.IntegerField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "bid_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="firesale.bid"
                    ),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firesale.category",
                    ),
                ),
                (
                    "image_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="firesale.image"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("street_name", models.CharField(max_length=100)),
                ("house_number", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("postal_code", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LogIn",
            fields=[
                (
                    "email",
                    models.CharField(max_length=320, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=64)),
                ("phone", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=7)),
                ("birthday", models.DateField()),
                ("bio", models.CharField(max_length=1000)),
                ("login", models.BooleanField(default=False)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="firesale.login"
                    ),
                ),
                (
                    "image_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="firesale.image"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                        default="Unpaid",
                        max_length=10,
                    ),
                ),
                (
                    "bid_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="firesale.bid"
                    ),
                ),
                (
                    "buyer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_as_buyer",
                        to="firesale.member",
                    ),
                ),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="firesale.item"
                    ),
                ),
                (
                    "seller_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_as_seller",
                        to="firesale.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField()),
                ("comment", models.CharField(max_length=1000)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "from_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_sent",
                        to="firesale.member",
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="firesale.order"
                    ),
                ),
                (
                    "to_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_recieved",
                        to="firesale.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("message", models.CharField(max_length=1000)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("read", "Read"), ("unread", "Unread")],
                        default="unread",
                        max_length=10,
                    ),
                ),
                (
                    "receiver_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="firesale.member",
                    ),
                ),
                (
                    "sender_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="firesale.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="location_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="firesale.location"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="member_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_listings",
                to="firesale.member",
            ),
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="firesale.item"
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_favorites",
                        to="firesale.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bid",
            name="item_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="firesale.item"
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="member_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="firesale.member",
            ),
        ),
    ]
