# Generated by Django 4.2.1 on 2023-05-22 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("firesale", "0004_remove_member_email_remove_member_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
