# Generated by Django 4.2.1 on 2023-05-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firesale", "0005_member_creation_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_url", models.CharField(max_length=1000)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_picture",
                        to="firesale.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_url", models.CharField(max_length=1000)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_image",
                        to="firesale.item",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="item",
            name="image_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="firesale.itemimage",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="image_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="firesale.memberimage",
            ),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
