# Generated by Django 4.1.6 on 2023-05-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0006_memberimage_itemimage_alter_item_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
