# Generated by Django 4.1.6 on 2023-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0007_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
