# Generated by Django 4.1.6 on 2023-05-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0008_item_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
