# Generated by Django 4.2.1 on 2023-05-26 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firesale", "0015_remove_item_location_item_item_location_and_more"),
        ("firesale", "0015_remove_message_status_alter_message_receiver_and_more"),
    ]

    operations = []
