# Generated by Django 4.2.1 on 2023-05-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firesale", "0017_message_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="item",
        ),
        migrations.AddField(
            model_name="message",
            name="bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="firesale.bid",
            ),
        ),
    ]
