# Generated by Django 4.1.6 on 2023-05-29 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firesale', '0018_remove_message_item_message_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='from_member',
        ),
        migrations.RemoveField(
            model_name='review',
            name='to_member',
        ),
        migrations.AddField(
            model_name='review',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_sent', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='to_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
