# Generated by Django 4.2.1 on 2023-05-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firesale", "0019_contact_payment_delete_mydata_remove_order_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.CharField(default="sunnak20@ru.is", max_length=100),
            preserve_default=False,
        ),
    ]
