# Generated by Django 4.2.1 on 2023-05-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firesale", "0020_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="card_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="cvc",
            field=models.IntegerField(),
        ),
    ]
