# Generated by Django 4.2.1 on 2023-05-27 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firesale", "0021_alter_payment_card_number_alter_payment_cvc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberimage",
            name="member",
        ),
        migrations.AlterField(
            model_name="favorite",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.DeleteModel(
            name="MemberImage",
        ),
    ]
