# Generated by Django 4.2.1 on 2023-05-29 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firesale", "0022_remove_memberimage_member_alter_favorite_member_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="card_number",
            field=models.CharField(max_length=16),
        ),
        migrations.AddField(
            model_name="review",
            name="from_member",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="to_member",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_recieved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="firesale.order"
            ),
        ),
    ]
