# Generated by Django 4.2.1 on 2023-05-30 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "firesale",
            "0023_alter_payment_card_number_alter_review_from_member_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="to_member",
            new_name="to_user",
        ),
        migrations.RemoveField(
            model_name="review",
            name="from_member",
        ),
        migrations.AddField(
            model_name="review",
            name="from_user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
