# Generated by Django 4.2.1 on 2023-05-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firesale", "0025_remove_item_image_remove_itemimage_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemimage",
            name="item",
            field=models.ForeignKey(
                default=58,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="firesale.item",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="image_urls",
            field=models.ManyToManyField(
                related_name="images", to="firesale.itemimage"
            ),
        ),
    ]
