# Generated by Django 4.1.6 on 2023-05-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0026_itemimage_item_alter_item_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='house_number',
            field=models.IntegerField(null=True),
        ),
    ]
