# Generated by Django 4.2.1 on 2023-06-01 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firesale", "0028_averagerating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AverageRating",
        ),
    ]
