# Generated by Django 4.2.1 on 2023-06-02 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firesale", "0029_delete_averagerating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
