INSERT INTO firesale_category (name) VALUES('Children')
INSERT INTO firesale_category (name) VALUES('Clothing')
INSERT INTO firesale_category (name) VALUES('Electronics')
INSERT INTO firesale_category (name) VALUES('Entertainment')
INSERT INTO firesale_category (name) VALUES('Housing')
INSERT INTO firesale_category (name) VALUES('Home')
INSERT INTO firesale_category (name) VALUES('Industry')
INSERT INTO firesale_category (name) VALUES('Jobs')
INSERT INTO firesale_category (name) VALUES('Pets')
INSERT INTO firesale_category (name) VALUES('Spare parts')
INSERT INTO firesale_category (name) VALUES('Sports and Health')
INSERT INTO firesale_category (name) VALUES('Vehicle')
